server:
  port: ${PORT:8080}
  error:
    include-stacktrace: never

spring:
  liquibase:
    change-log: db/db.changelog-master.xml
    default-schema: ${DB_SCHEMA:world_traveller}
    liquibase-schema: ${DB_SCHEMA:world_traveller}
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    url: ${DB_URL:jdbc:postgresql://localhost:5432/world_traveller}
    hikari:
      schema:
  jpa:
    database: POSTGRESQL
    show-sql: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: ${DB_SCHEMA:world_traveller}
  security:
    jwt:
      secret: ${JWT_SECRET:secret}
      issuer: ${JWT_ISSUER:world_traveller}

web:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}
    allowed-methods: GET, POST, PATCH, PUT, DELETE, OPTIONS, HEAD
    max-age: 3600
